# Generated by Django 6.1 on 2026-09-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_hot_deal',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
